<?php
	$provinsi = array(
	array("value"=>"1","text"=>"Indonesia"),
	array("value"=>"1","text"=>"Aceh"),
	array("value"=>"1","text"=>"Sumatera Utara"),
	array("value"=>"1","text"=>"Sumatera Barat"),
	array("value"=>"1","text"=>"Riau"),
	array("value"=>"1","text"=>"Jambi"),
	array("value"=>"1","text"=>"Sumatera Selatan"),
	array("value"=>"1","text"=>"Bengkulu"),
	array("value"=>"1","text"=>"Lampung"),
	array("value"=>"1","text"=>"Kepulauan Bangka Belitung"),
	array("value"=>"1","text"=>"Kepulauan Riau"),
	array("value"=>"1","text"=>"Jawa"),
	array("value"=>"1","text"=>"Jakarta"),
	array("value"=>"1","text"=>"Yogyakarta"),
	array("value"=>"1","text"=>"Jawa Barat"),
	array("value"=>"1","text"=>"Jawa Tengah"),
	array("value"=>"1","text"=>"Jawa Timur"),
	array("value"=>"1","text"=>"Banten"),
	array("value"=>"1","text"=>"Sunda Kecil"),
	array("value"=>"1","text"=>"Bali"),
	array("value"=>"1","text"=>"Nusa Tenggara Timur"),
	array("value"=>"1","text"=>"Nusa Tenggara Barat"),
	array("value"=>"1","text"=>"Kalimantan"),
	array("value"=>"1","text"=>"Kalimantan Barat"),
	array("value"=>"1","text"=>"Kalimantan Tengah"),
	array("value"=>"1","text"=>"Kalimantan Selatan"),
	array("value"=>"1","text"=>"Kalimantan Timur"),
	array("value"=>"1","text"=>"Kalimantan Utara"),
	array("value"=>"1","text"=>"Sulawesi"),
	array("value"=>"1","text"=>"Sulawesi Utara"),
	array("value"=>"1","text"=>"Sulawesi Tengah"),
	array("value"=>"1","text"=>"Sulawesi Selatan"),
	array("value"=>"1","text"=>"Sulawesi Tenggara"),
	array("value"=>"1","text"=>"Sulawesi Barat"),
	array("value"=>"1","text"=>"Gorontalo"),
	array("value"=>"1","text"=>"Maluku"),
	array("value"=>"1","text"=>"Maluku Utara"),
	array("value"=>"1","text"=>"Papua"),
	array("value"=>"1","text"=>"Papua Barat"));

	header('Content-Type: application/json');
	echo json_encode($provinsi);
?>